In [1]:
from transformers import CamembertForSequenceClassification, CamembertTokenizer, pipeline, CamembertModel
import torch

In [2]:
model_name = "camembert-base"

In [103]:
tokenizer = CamembertTokenizer.from_pretrained(model_name)
#cam = CamembertModel.from_pretrained(model_name)

In [4]:
tweets = ["J'ai passé une super journée", "Grosses galères aujourd'hui"]

In [5]:
tweet = tweets[0]

In [6]:
tokenizer.tokenize(tweet)
tokenizer.encode(tweet)
tokenizer.decode(tokenizer.encode(tweet))

"<s> J'ai passé une super journée</s>"

In [7]:
classifier = pipeline('sentiment-analysis', model=model_name, tokenizer=tokenizer)

Some weights of the model checkpoint at camembert-base were not used when initializing CamembertForSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight', 'roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing CamembertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing CamembertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at camembert-base and are newly initialized: ['classifier.dense.weight'

In [8]:
classifier("Il fait très beau !")

[{'label': 'LABEL_1', 'score': 0.5017223358154297}]

In [9]:
camembert_fill_mask  = pipeline("fill-mask", model=model_name, tokenizer=tokenizer)
camembert_fill_mask("Le camembert est <mask> :)")

Some weights of CamembertForMaskedLM were not initialized from the model checkpoint at camembert-base and are newly initialized: ['lm_head.decoder.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


[{'sequence': '<s> Le camembert est délicieux :)</s>',
  'score': 0.49091020226478577,
  'token': 7200,
  'token_str': '▁délicieux'},
 {'sequence': '<s> Le camembert est excellent :)</s>',
  'score': 0.10556937754154205,
  'token': 2183,
  'token_str': '▁excellent'},
 {'sequence': '<s> Le camembert est succulent :)</s>',
  'score': 0.034533143043518066,
  'token': 26202,
  'token_str': '▁succulent'},
 {'sequence': '<s> Le camembert est meilleur :)</s>',
  'score': 0.03303135931491852,
  'token': 528,
  'token_str': '▁meilleur'},
 {'sequence': '<s> Le camembert est parfait :)</s>',
  'score': 0.030076511204242706,
  'token': 1654,
  'token_str': '▁parfait'}]

In [10]:
camembert_fill_mask("J'aime les <mask> bleus!")

[{'sequence': "<s> J'aime les yeux bleus!</s>",
  'score': 0.0990937277674675,
  'token': 605,
  'token_str': '▁yeux'},
 {'sequence': "<s> J'aime les cheveux bleus!</s>",
  'score': 0.04541785269975662,
  'token': 1277,
  'token_str': '▁cheveux'},
 {'sequence': "<s> J'aime les chats bleus!</s>",
  'score': 0.03782883286476135,
  'token': 6289,
  'token_str': '▁chats'},
 {'sequence': "<s> J'aime les poissons bleus!</s>",
  'score': 0.035177621990442276,
  'token': 4831,
  'token_str': '▁poissons'},
 {'sequence': "<s> J'aime les oiseaux bleus!</s>",
  'score': 0.026914037764072418,
  'token': 5709,
  'token_str': '▁oiseaux'}]

In [81]:
encoding = tokenizer(tweets, return_tensors='pt', padding=True, truncation=True)
input_ids = encoding['input_ids']
attention_mask = encoding['attention_mask']

In [98]:
outputs = camembert(input_ids, attention_mask=attention_mask, labels=labels)

In [99]:
outputs

SequenceClassifierOutput(loss=tensor(0.7065, grad_fn=<NllLossBackward>), logits=tensor([[ 0.0557, -0.1002],
        [ 0.0349, -0.0768]], grad_fn=<AddmmBackward>), hidden_states=None, attentions=None)

In [105]:
tokenizer.add_tokens(['onco'])

1

In [123]:
text = 'un test astrologie oncologie logie regardées tromato'
print(tokenizer.tokenize(text))
print(tokenizer.encode(text)[1:-1])

['▁un', '▁test', '▁', 'astrologie', 'onco', '▁', 'logie', '▁', 'logie', '▁regardé', 'es', '▁t', 'roma', 'to']
[23, 2006, 21, 15174, 32005, 21, 4736, 21, 4736, 8031, 80, 271, 12295, 891]


In [112]:
tokenizer.get_vocab()

{'<s>NOTUSED': 0,
 '<pad>': 1,
 '</s>NOTUSED': 2,
 '<unk>': 4,
 '<s>': 5,
 '</s>': 6,
 ',': 7,
 '▁de': 8,
 '.': 9,
 's': 10,
 "'": 11,
 '’': 12,
 '▁la': 13,
 '▁et': 14,
 '▁à': 15,
 '▁le': 16,
 '▁l': 17,
 '▁d': 18,
 '▁les': 19,
 '▁des': 20,
 '▁': 21,
 '▁en': 22,
 '▁un': 23,
 '▁pour': 24,
 '▁du': 25,
 '-': 26,
 '▁que': 27,
 '▁une': 28,
 '▁dans': 29,
 '▁est': 30,
 '▁qui': 31,
 '▁sur': 32,
 '▁a': 33,
 '▁pas': 34,
 'e': 35,
 '▁au': 36,
 '▁par': 37,
 '▁(': 38,
 '▁vous': 39,
 '▁plus': 40,
 'est': 41,
 '▁avec': 42,
 '▁:': 43,
 '▁ce': 44,
 '▁ne': 45,
 '▁qu': 46,
 '▁ou': 47,
 '▁se': 48,
 '▁n': 49,
 '▁je': 50,
 '▁il': 51,
 '▁s': 52,
 ')': 53,
 '▁Le': 54,
 'a': 55,
 '▁sont': 56,
 '...': 57,
 '▁son': 58,
 'un': 59,
 '▁c': 60,
 '▁La': 61,
 'il': 62,
 '▁nous': 63,
 '▁«': 64,
 '▁mais': 65,
 '▁tout': 66,
 '▁-': 67,
 '▁aux': 68,
 '▁Il': 69,
 'une': 70,
 '▁L': 71,
 '▁bien': 72,
 'ai': 73,
 '▁Les': 74,
 '▁votre': 75,
 '▁j': 76,
 '▁sa': 77,
 '▁cette': 78,
 '▁comme': 79,
 'es': 80,
 'r': 81,
 '▁fait': 82,
 

In [52]:
encoding = tokenizer(['test rhume oncologie'], return_tensors='pt', padding=True, truncation=True)
input_ids = encoding['input_ids']
attention_mask = encoding['attention_mask']

In [114]:
voc = set(tokenizer.get_vocab().keys())

In [138]:
'▁lapin' in voc

True

In [145]:
from time import time

In [146]:
start = time()
tokenizer.tokenize("Aujourd'hui")
print(time() - start)

0.0027472972869873047


In [147]:
tokenizer.add_tokens([f'unk{i}' for i in range(1000)])

1000

In [148]:
start = time()
tokenizer.tokenize("Aujourd'hui")
print(time() - start)

0.012057065963745117


In [124]:
import re

In [131]:
re.findall(r'\w+', "Hey, you - what are you doing here!?")

['Hey', 'you', 'what', 'are', 'you', 'doing', 'here']

In [88]:
camembert.resize_token_embeddings(34010)

Embedding(34010, 768)

In [143]:
camembert.get_input_embeddings().num_embeddings

34010

In [57]:
camembert(input_ids, attention_mask=attention_mask)

SequenceClassifierOutput(loss=None, logits=tensor([[-0.0053, -0.0264]], grad_fn=<AddmmBackward>), hidden_states=None, attentions=None)

In [100]:
camembert.get_input_embeddings().weight.sum(axis=1)

tensor([ -7.7356, -11.9176,  -0.1520,  ...,  -0.5433,   0.1731,  -0.3620],
       grad_fn=<SumBackward1>)

In [86]:
input = torch.tensor(tokenizer.encode('test simple simple'))
camembert.get_input_embeddings()(input)

tensor([[-1.2213e-02, -3.9306e-02, -3.1889e-04,  ..., -1.3756e-03,
         -3.9666e-05, -3.3056e-03],
        [-1.6021e-02, -2.2969e-02, -1.2812e-02,  ..., -1.3113e-02,
         -3.1222e-02, -6.5595e-04],
        [-3.2210e-03,  1.8273e-03, -1.8213e-02,  ...,  2.4443e-02,
         -8.7075e-04,  2.2326e-02],
        [-3.2210e-03,  1.8273e-03, -1.8213e-02,  ...,  2.4443e-02,
         -8.7075e-04,  2.2326e-02],
        [ 3.0302e-02, -1.6117e-02, -1.0288e-02,  ..., -1.9234e-02,
         -4.6506e-04,  8.6418e-03]], grad_fn=<EmbeddingBackward>)

In [82]:
input = torch.tensor(tokenizer.encode('test simple simple'))
camembert.get_input_embeddings()(input)

tensor([[ 0.0263, -0.0184,  0.0415,  ..., -0.0092, -0.0796,  0.0009],
        [-0.0918, -0.0601, -0.2429,  ...,  0.0967, -0.0688, -0.0571],
        [ 0.1105,  0.0779, -0.0875,  ..., -0.0956,  0.0994, -0.0822],
        [ 0.1105,  0.0779, -0.0875,  ..., -0.0956,  0.0994, -0.0822],
        [ 0.0840, -0.0480, -0.0378,  ..., -0.0329, -0.0510,  0.0410]],
       grad_fn=<EmbeddingBackward>)

In [18]:
tokenizer.SPECIAL_TOKENS_ATTRIBUTES

['bos_token',
 'eos_token',
 'unk_token',
 'sep_token',
 'pad_token',
 'cls_token',
 'mask_token',
 'additional_special_tokens']

In [35]:
import pandas

In [38]:
df = pandas.read_csv('../french_tweets_short.csv')

In [39]:
from transformers import AdamW

In [40]:
labels = list(df.label)
texts = list(df.text)

encoding = tokenizer(texts, return_tensors='pt', padding=True, truncation=True)
input_ids = encoding['input_ids']
attention_mask = encoding['attention_mask']
labels = torch.tensor(labels).unsqueeze(0)

In [59]:
camembert = CamembertForSequenceClassification.from_pretrained(model_name, num_labels=2)
optimizer = AdamW(camembert.parameters(), lr=1e-5)
classifier = pipeline('sentiment-analysis', model=camembert, tokenizer=tokenizer)

Some weights of the model checkpoint at camembert-base were not used when initializing CamembertForSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight', 'roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing CamembertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing CamembertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at camembert-base and are newly initialized: ['classifier.dense.weight'

In [50]:
camembert(input_ids, attention_mask=attention_mask, labels=labels)

Embedding(32005, 768, padding_idx=1)

In [166]:
epochs = 10

for _ in range(epochs):
    outputs = camembert(input_ids, attention_mask=attention_mask, labels=labels)
    loss = outputs.loss
    print(loss)
    loss.backward()
    optimizer.step()

tensor(0.4683, grad_fn=<NllLossBackward>)
tensor(0.4551, grad_fn=<NllLossBackward>)
tensor(0.4425, grad_fn=<NllLossBackward>)
tensor(0.4303, grad_fn=<NllLossBackward>)
tensor(0.4185, grad_fn=<NllLossBackward>)
tensor(0.4071, grad_fn=<NllLossBackward>)
tensor(0.3960, grad_fn=<NllLossBackward>)
tensor(0.3850, grad_fn=<NllLossBackward>)
tensor(0.3742, grad_fn=<NllLossBackward>)
tensor(0.3633, grad_fn=<NllLossBackward>)


In [167]:
classifier(texts)

[{'label': 'LABEL_0', 'score': 0.6743533611297607},
 {'label': 'LABEL_0', 'score': 0.6857601404190063},
 {'label': 'LABEL_0', 'score': 0.6726309061050415},
 {'label': 'LABEL_0', 'score': 0.6749323606491089},
 {'label': 'LABEL_0', 'score': 0.6603058576583862},
 {'label': 'LABEL_0', 'score': 0.6522192358970642},
 {'label': 'LABEL_0', 'score': 0.6360929012298584},
 {'label': 'LABEL_1', 'score': 0.7538371086120605},
 {'label': 'LABEL_1', 'score': 0.7436507940292358},
 {'label': 'LABEL_1', 'score': 0.7174726724624634},
 {'label': 'LABEL_1', 'score': 0.7531613707542419},
 {'label': 'LABEL_1', 'score': 0.674791157245636},
 {'label': 'LABEL_1', 'score': 0.6971939206123352},
 {'label': 'LABEL_1', 'score': 0.7637169361114502},
 {'label': 'LABEL_1', 'score': 0.750148355960846},
 {'label': 'LABEL_1', 'score': 0.7579358816146851}]

In [177]:
outputs = camembert(input_ids, attention_mask=attention_mask, labels=labels)

In [179]:
outputs.logits

tensor([[ 0.3852, -0.3428],
        [ 0.4054, -0.3750],
        [ 0.3783, -0.3418],
        [ 0.3592, -0.3714],
        [ 0.3408, -0.3239],
        [ 0.3279, -0.3009],
        [ 0.2998, -0.2586],
        [-0.5728,  0.5464],
        [-0.5110,  0.5540],
        [-0.4302,  0.5017],
        [-0.5568,  0.5587],
        [-0.3349,  0.3950],
        [-0.3959,  0.4381],
        [-0.5581,  0.6151],
        [-0.5186,  0.5808],
        [-0.5655,  0.5758]], grad_fn=<AddmmBackward>)

In [186]:
torch.softmax(outputs.logits, dim=1).argmax(axis=1).tolist()

[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [188]:
import os

In [189]:
os.sep.join(os.getcwd().split(os.sep)[0 : os.getcwd().split(os.sep).index("French-Transformers") + 1])

'/Users/quentinblampey/cs/French-Transformers'